src/PruebaUnoAgioGlobal.Web/Controllers/FilesManagementController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaUnoAgioGlobal.Web.ApplicationServices.Interfaces;
using PruebaUnoAgioGlobal.Web.ModelsViews;
using System.Threading.Tasks;

namespace PruebaUnoAgioGlobal.Web.Controllers
{
    /// <summary>
    /// Controller for flights management views.
    /// </summary>
    public class FilesManagementController : Controller
    {
        private readonly IFilesService _filesService;

        /// <summary>
        /// Generates a new instance of the Files Management Controller.
        /// </summary>
        /// <param name="filesService">Files application service.</param>
        public FilesManagementController(IFilesService filesService)
        {
            _filesService = filesService;
        }

        /// <summary>
        /// Loads the main files management view.
        /// </summary>
        /// <returns>Files management view.</returns>
        public IActionResult Index()
        {
            var fileUploadViewModel = new FileUploadViewModel()
            {
                FileTypes = _filesService.GetFileTypes(),
                UserRoles = _filesService.GetUserRoles(),
            };

            return View(fileUploadViewModel);
        }

        /// <summary>
        /// Uploads the files and show the file content in the loaded page.
        /// </summary>
        /// <returns>Upload file view.</returns>
        [HttpPost]
        public async Task<IActionResult> UploadFile(FileUploadViewModel model)
        {
            var readedTextFile = await _filesService.ReadTextFile(model);

            return View(readedTextFile);
        }
    }
}

src/PruebaUnoAgioGlobal.Web/Controllers/FlightsManagementController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PruebaUnoAgioGlobal.Web.ApplicationServices.Interfaces;
using PruebaUnoAgioGlobal.Web.ModelsApi.Flights.Requests;
using System.Threading.Tasks;

namespace PruebaUnoAgioGlobal.Web.Controllers
{
    /// <summary>
    /// Controller for flights management views.
    /// </summary>
    public class FlightsManagementController : Controller
    {
        private readonly IFlightsService _flightsService;

        /// <summary>
        /// Generates a new instance of the Flights Management Controller.
        /// </summary>
        /// <param name="flightsService">Flights application service.</param>
        public FlightsManagementController(IFlightsService flightsService)
        {
            _flightsService = flightsService;
        }

        /// <summary>
        /// Loads the main flight management view.
        /// </summary>
        /// <returns>Flight management view.</returns>
        public async Task<IActionResult> Index()
        {
            var flightsDtos = await _flightsService.GetAll();

            return View(flightsDtos);
        }

        /// <summary>
        /// Loads the create flight view.
        /// </summary>
        public IActionResult Create()
        {
            var createFlightRequest = new CreateFlightRequest();

            return View(createFlightRequest);
        }

        /// <summary>
        /// Stores a new flight.
        /// </summary>
        /// <param name="request">Request to create a new flight.</param>
        /// <returns>Redirect to index view.</returns>
        [HttpPost]
        public async Task<IActionResult> Create(CreateFlightRequest request)
        {
            var insertedId = await _flightsService.Insert(request);

            return new RedirectResult(Url.Action(nameof(Index)));
        }

        /// <summary>
        /// Loads the edit flight view.
        /// </summary>
        /// <returns>Flight edit view.</returns>
        public async Task<IActionResult> Edit(int flightId)
        {
            var getFlightByIdRequest = new GetFlightByIdRequest() { FlightId = flightId };

            var flightDto = await _flightsService.GetById(getFlightByIdRequest);

            return View(Mapper.Map<UpdateFlightRequest>(flightDto));
        }

        /// <summary>
        /// Updates a flight.
        /// </summary>
        /// <param name="request">Request to update a flight.</param>
        /// <returns>Redirect to index view.</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(UpdateFlightRequest request)
        {
            await _flightsService.Update(request);

            return new RedirectResult(Url.Action(nameof(Index)));
        }

        /// <summary>
        /// Deletes selected flight.
        /// </summary>
        /// <returns>Flight id for delete.</returns>
        /// <returns>Redirect to index view.</returns>
        public async Task<IActionResult> Delete(int flightId)
        {
            var deleteFlightRequest = new DeleteFlightRequest() { FlightId = flightId };

            await _flightsService.Delete(deleteFlightRequest);

            return new RedirectResult(Url.Action(nameof(Index)));
        }

        /// <summary>
        /// Loads the error view.
        /// </summary>
        /// <returns>Error view.</returns>
        public IActionResult Error()
        {
            return View();
        }
    }
}

src/PruebaUnoAgioGlobal.Web/Views/FilesManagement/Index.cshtml
@using  PruebaUnoAgioGlobal.Web.ModelsViews;
@using PruebaUnoAgioGlobal.Web.Enum;
@model FileUploadViewModel
@{
    ViewData["Title"] = "File Reader";
}

<h2>Reads New File</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="UploadFile" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FileType" class="control-label">File type</label><br />
                <select asp-for="FileType" asp-items="@Model.FileTypes" style="width:100%">
                    <option value="-1">Select file type</option>
                </select>
                <span asp-validation-for="FileType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserRole" class="control-label">User Role</label><br />
                <select asp-for="UserRole" asp-items="@Model.UserRoles" style="width:100%">
                    <option value="-1">Select role</option>
                </select>
                <span asp-validation-for="FileType" class="text-danger"></span>
            </div>            
            <div class="form-group" style="padding-top: 15px;">
                <label asp-for="AttachedFile" class="control-label">File to Upload</label>
                <input asp-for="AttachedFile" type="file" class="control-label" disabled="disabled" />
                <span asp-validation-for="AttachedFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="savebutton" type="submit" value="Save" class="btn btn-success" disabled="disabled" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {

            $('#FileType').change(function () {

                $('#AttachedFile').prop("disabled", "");

                if ($('#FileType').val() == "@(((int)FileTypesEnums.FileType.TEXT_FILE).ToString())" || 
                    $('#FileType').val() == "@(((int)FileTypesEnums.FileType.ENCRIPTED_TEXT_FILE).ToString())") {

                    $('#AttachedFile').attr('accept', 'text/plain');

                } else if ($('#FileType').val() == "@(((int)FileTypesEnums.FileType.XML_FILE).ToString())" ||
                           $('#FileType').val() == "@(((int)FileTypesEnums.FileType.ENCRIPTED_XML_FILE).ToString())") {

                    $('#AttachedFile').attr('accept', 'text/xml');
                    
                } else if ($('#FileType').val() == "@(((int)FileTypesEnums.FileType.JSON_FILE).ToString())" ||
                           $('#FileType').val() == "@(((int)FileTypesEnums.FileType.ENCRIPTED_JSON_FILE).ToString())") {

                    $('#AttachedFile').attr('accept', '.json');                
                }
                
                else { 

                    $('#AttachedFile').prop("disabled", "disabled");
                }
            });

            $('#AttachedFile').change(function () {

                if ($('#UserRole').val() > 0) {

                    $('#savebutton').prop("disabled", "");
                }
            });

            $('#UserRole').change(function () {

                if ($('#UserRole').val() > 0 && $('#AttachedFile').val() != '') {

                    $('#savebutton').prop("disabled", "");
                }                    
            });
        });
    </script>
}

src/PruebaUnoAgioGlobal.Web/Views/FilesManagement/UploadFile.cshtml
@using  PruebaUnoAgioGlobal.Web.ModelsViews;
@model FileUploadedViewModel
@{
    ViewData["Title"] = "File Readed";
}

<h2>Content of file readed</h2>
<hr />

<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <label asp-for="TextFileReaded" class="control-label">Content of the readed file</label>
            <br />
            <textarea asp-for="TextFileReaded" class="control-label" rows="15" cols="150" style="max-width:100%"></textarea>
        </div>
        <div>
            <a asp-action="Index">Back to File Upload</a>
        </div>
    </div>    
</div>

src/PruebaUnoAgioGlobal.Web/Views/FlightsManagement/Create.cshtml
@using PruebaUnoAgioGlobal.Web.ModelsApi.Flights.Requests;
@model CreateFlightRequest

@{
    ViewData["Title"] = "Create New Flight";
}

<h2>Create New Flight</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label">Flight Code</label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OriginAirportId" class="control-label">Origin Airport</label>
                <select asp-for="OriginAirportId" class="form-control"></select>
                <span asp-validation-for="OriginAirportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationAirportId" class="control-label">Destination Airport</label>
                <select asp-for="DestinationAirportId" class="form-control"></select>
                <span asp-validation-for="DestinationAirportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AirlineId" class="control-label">Airline</label>
                <select asp-for="AirlineId" class="form-control"></select>
                <span asp-validation-for="AirlineId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {

            $('#AirlineId').append(new Option('', '', true, true));

            $.get("@Url.Action("../api/airlines")", function (data) {

                $.each(data, function (index, value) {

                    $('#AirlineId').append(new Option(value.codeAndName, value.airlineId));
                });
            });

            $('#OriginAirportId').append(new Option('', '', true, true));
            $('#DestinationAirportId').append(new Option('', '', true, true));

            $.get("@Url.Action("../api/airports")", function (data) {

                $.each(data, function (index, value) {

                    $('#OriginAirportId').append(new Option(value.codeAndName, value.airportId));
                    $('#DestinationAirportId').append(new Option(value.codeAndName, value.airportId));
                });
            });           
        });
    </script>
}

src/PruebaUnoAgioGlobal.Web/Views/FlightsManagement/Edit.cshtml
@using PruebaUnoAgioGlobal.Web.ModelsApi.Flights.Requests;
@model UpdateFlightRequest

@{
    ViewData["Title"] = "Edit " + Model.Code + " Flight";
}

<h2>Create New Flight</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FlightId" />
            <div class="form-group">
                <label asp-for="Code" class="control-label">Flight Code</label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OriginAirportId" class="control-label">Origin Airport</label>
                <select asp-for="OriginAirportId" class="form-control" data-content="@Model.OriginAirportId"></select>
                <span asp-validation-for="OriginAirportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationAirportId" class="control-label">Destination Airport</label>
                <select asp-for="DestinationAirportId" class="form-control" data-content="@Model.DestinationAirportId"></select>
                <span asp-validation-for="DestinationAirportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AirlineId" class="control-label">Airline</label>
                <select asp-for="AirlineId" class="form-control" data-content="@Model.AirlineId"></select>
                <span asp-validation-for="AirlineId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {

            $('#AirlineId').append(new Option('', ''));

            $.get("@Url.Action("../api/airlines")", function (data) {

                $.each(data, function (index, value) {

                    $('#AirlineId').append(new Option(value.codeAndName, value.airlineId, false, value.airlineId == $('#AirlineId').attr('data-content')));
                });
            });

            $('#OriginAirportId').append(new Option('', ''));
            $('#DestinationAirportId').append(new Option('', ''));

            $.get("@Url.Action("../api/airports")", function (data) {

                $.each(data, function (index, value) {

                    $('#OriginAirportId').append(new Option(value.codeAndName, value.airportId, false, value.airportId == $('#OriginAirportId').attr('data-content')));
                    $('#DestinationAirportId').append(new Option(value.codeAndName, value.airportId, false, value.airportId == $('#DestinationAirportId').attr('data-content')));
                });
            });
        });
    </script>
}

src/PruebaUnoAgioGlobal.Web/Views/FlightsManagement/Index.cshtml
@using PruebaUnoAgioGlobal.Web.ModelsApi.Flights.Responses;
@model List<FlightListDTO>;
@{
    ViewData["Title"] = "Flights Management";
}

<div class="row">
    <div class="col-md-12">
        <div class="col-md-6" style="padding-top: 15px; padding-bottom:15px">
            <h2>Current Flights</h2>
        </div>
        <div class="col-md-6; text-right" style="padding-top: 15px; padding-bottom:15px;">
            <a class="btn btn-primary btn-lg" role="button" asp-controller="FlightsManagement" asp-action="Create">Create New Flight</a>
        </div>
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="text-right">#</th>
                        <th scope="col">Code</th>
                        <th scope="col">Airline</th>
                        <th scope="col">Origin Airport</th>
                        <th scope="col">Destination Airport</th>
                        <th scope="col" class="text-right">Distance</th>
                        <th scope="col" class="text-right">Fuel Consumption</th>
                        <th scope="col" class="text-right"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var flightListDTO in Model)
                {
                    <tr>
                        <th scope="row" class="text-right"><a asp-controller="FlightsManagement" asp-action="Edit" asp-route-flightId="@flightListDTO.FlightId">@flightListDTO.FlightId</a></th>
                        <td>@flightListDTO.Code</td>
                        <td>@flightListDTO.Airline</td>
                        <td>@flightListDTO.OriginAirport</td>
                        <td>@flightListDTO.DestinationAirport</td>
                        <td class="text-right">@flightListDTO.Distance.ToString("N0")</td>
                        <td class="text-right">@flightListDTO.FuelConsumption.ToString("N0")</td>
                        <td><a asp-controller="FlightsManagement" asp-action="Delete" asp-route-flightId="@flightListDTO.FlightId"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
                    </tr>
            }
                </tbody>
            </table>
        </div>
    </div>

src/PruebaUnoAgioGlobal.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaUnoAgioGlobal.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="FlightsManagement" asp-action="Index" class="navbar-brand">Prueba Agio Global</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="FlightsManagement" asp-action="Index">Flights</a></li>
                    <li><a href="./swagger">Swagger</a></li>
                    <li><a asp-area="" asp-controller="FilesManagement" asp-action="Index">Files</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Alejandro Garrote De La Torre</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>